### ISSUE TITLE
Sytnax Discussion related to phpcs & phpcbf

### ISSUE THREAD

**Issue by svpernova09** [svpernova09/short-attr#1]
```sh
$ php --v
PHP 7.4.8 (cli) (built: Jul 13 2020 16:46:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.8, Copyright (c), by Zend Technologies
```
##  phpcs --standard=PSR12 atat-syntax.php

```sh
$ phpcs --standard=PSR12 atat-syntax.php
FILE: /home/halo/LinuxCode/short-attr/atat-syntax.php
FOUND 7 ERRORS AND 1 WARNING AFFECTING 6 LINES

  1 | WARNING | [ ] A file should declare new symbols (classes, functions, constants, etc.) and cause no other side effects, or it should execute logic
    |         |     with side effects, but should not do both. The first symbol is defined on line 4 and the first side effect is on line 3.
  4 | ERROR   | [ ] Each class must be in a namespace of at least one level (a top-level vendor name)
  9 | ERROR   | [x] Opening brace should be on a new line
  9 | ERROR   | [x] Closing brace must be on a line by itself
 12 | ERROR   | [x] Parentheses must be used when instantiating a new class
 12 | ERROR   | [x] Closing brace must be on a line by itself
 14 | ERROR   | [x] Closing brace must be on a line by itself
 16 | ERROR   | [x] Expected 1 newline at end of file; 0 found

PHPCBF CAN FIX THE 6 MARKED SNIFF VIOLATIONS AUTOMATICALLY

Time: 19ms; Memory: 6MB
```

## phpcs --standard=PSR12 rusty-syntax.php

```sh
phpcs --standard=PSR12 rusty-syntax.php

FILE: /home/halo/LinuxCode/short-attr/rusty-syntax.php

FOUND 3 ERRORS AND 1 WARNING AFFECTING 4 LINES

  1 | WARNING | [ ] A file should declare new symbols (classes, functions, constants, etc.) and cause no other side effects, or it should execute logic
    |         |     with side effects, but should not do both. The first symbol is defined on line 4 and the first side effect is on line 12.
  4 | ERROR   | [ ] Each class must be in a namespace of at least one level (a top-level vendor name)
 12 | ERROR   | [x] Parentheses must be used when instantiating a new class
 16 | ERROR   | [x] Expected 1 newline at end of file; 0 found

PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY

Time: 19ms; Memory: 6MB
```

## phpcbf --standard=PSR12 atat-syntax.php
```sh
$ phpcbf --standard=PSR12 atat-syntax.php

PHPCBF RESULT SUMMARY
----------------------------------------------------------------------
FILE                                                  FIXED  REMAINING
----------------------------------------------------------------------
/home/halo/LinuxCode/short-attr/atat-syntax.php       6      2
----------------------------------------------------------------------
A TOTAL OF 6 ERRORS WERE FIXED IN 1 FILE
----------------------------------------------------------------------

Time: 23ms; Memory: 6MB
```

## phpcbf --standard=PSR12 rusty-syntax.php
```sh
$ phpcbf --standard=PSR12 rusty-syntax.php

PHPCBF RESULT SUMMARY
----------------------------------------------------------------------
FILE                                                  FIXED  REMAINING
----------------------------------------------------------------------
/home/halo/LinuxCode/short-attr/rusty-syntax.php      2      2
----------------------------------------------------------------------
A TOTAL OF 2 ERRORS WERE FIXED IN 1 FILE
----------------------------------------------------------------------

Time: 20ms; Memory: 6MB
```

**Comment by jrfnl** [comment]
@svpernova09 Could you please share the files you used to run PHPCS over ?

**Comment by svpernova09** [comment]
https://github.com/svpernova09/short-attr/blob/master/atat-syntax.php

```
<?php

@@ExampleAttribute
class Foo
{
    @@ExampleAttribute
    public const FOO = 'foo';

    public function foo(@@ExampleAttribute Type $bar) {}
}

$object = new @@ExampleAttribute class () {};

$f1 = @@ExampleAttribute function () {};

$f2 = @@ExampleAttribute fn() => 1;
```
https://github.com/svpernova09/short-attr/blob/master/rusty-syntax.php

```
<?php

#[ExampleAttribute]
class Foo
{
    #[ExampleAttribute]
    public const FOO = 'foo';

    public function foo(#[ExampleAttribute] Type $bar) {}
}
 
$object = new #[ExampleAttribute] class () {};
 
$f1 = #[ExampleAttribute] function () {};

$f2 = #[ExampleAttribute] fn() => 1;
```
These examples were taken from the RFC https://wiki.php.net/rfc/shorter_attribute_syntax_change

**Comment by jrfnl** [comment]
### Detailed outline of the expected effects of the different syntaxes

The below examples are also [taken from the RFC](https://wiki.php.net/rfc/shorter_attribute_syntax#confusion_with_shift_operators_and_const_arguments) and I have adjusted the formatting of the second line of each with some alternative spacing in such a way that I expect it would cause violations when running PHPCS against PSR12.

```php
<?php

class Foo
{
    <<Attr1(2 * 3 + 3), Bar(4 + 5 * 2)>>
    <<Attr2 ( 2*( 3+3 ),Baz,( 4+5 )*2 )>>
    public function brackets() {}

    @@Attr1(2 * 3 + 3), Bar(4 + 5 * 2)
    @@Attr2 ( 2*( 3+3 ) ,Baz,( 4+5 )*2 )
    public function atat() {}

    #[Attr1(2 * 3 + 3), Bar(4 + 5 * 2)]
    #[ Attr2 ( 2*( 3+3 ),Baz,( 4+5 )*2 ) ]
    public function hash() {}
}
```

This results in the following errors for the first code sample:
```
  5 | ERROR | [x] Expected at least 1 space after "<<"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceAfter)
  5 | ERROR | [x] Expected at least 1 space before ">>"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceBefore)
  6 | ERROR | [x] Expected at least 1 space after "<<"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceAfter)
  6 | ERROR | [x] Space before opening parenthesis of function call prohibited (PSR2.Methods.FunctionCallSignature.SpaceBeforeOpenBracket)
  6 | ERROR | [x] Space after opening parenthesis of function call prohibited (PSR2.Methods.FunctionCallSignature.SpaceAfterOpenBracket)
  6 | ERROR | [x] Expected 0 spaces before closing parenthesis; 1 found (PSR2.Methods.FunctionCallSignature.SpaceBeforeCloseBracket)
  6 | ERROR | [x] Expected at least 1 space before "*"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceBefore)
  6 | ERROR | [x] Expected at least 1 space after "*"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceAfter)
  6 | ERROR | [x] Expected at least 1 space before "+"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceBefore)
  6 | ERROR | [x] Expected at least 1 space after "+"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceAfter)
  6 | ERROR | [x] No space found after comma in argument list (Generic.Functions.FunctionCallArgumentSpacing.NoSpaceAfterComma)
  6 | ERROR | [x] No space found after comma in argument list (Generic.Functions.FunctionCallArgumentSpacing.NoSpaceAfterComma)
  6 | ERROR | [x] Expected at least 1 space before "+"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceBefore)
  6 | ERROR | [x] Expected at least 1 space after "+"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceAfter)
  6 | ERROR | [x] Expected at least 1 space before "*"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceBefore)
  6 | ERROR | [x] Expected at least 1 space after "*"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceAfter)
  6 | ERROR | [x] Expected at least 1 space before ">>"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceBefore)
  7 | ERROR | [x] Opening brace should be on a new line (Squiz.Functions.MultiLineFunctionDeclaration.BraceOnSameLine)
  7 | ERROR | [x] Closing brace must be on a line by itself (Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore)
```

These for the second code sample:
```
 10 | ERROR | [x] Space before opening parenthesis of function call prohibited (PSR2.Methods.FunctionCallSignature.SpaceBeforeOpenBracket)
 10 | ERROR | [x] Space after opening parenthesis of function call prohibited (PSR2.Methods.FunctionCallSignature.SpaceAfterOpenBracket)
 10 | ERROR | [x] Expected 0 spaces before closing parenthesis; 1 found (PSR2.Methods.FunctionCallSignature.SpaceBeforeCloseBracket)
 10 | ERROR | [x] Expected at least 1 space before "*"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceBefore)
 10 | ERROR | [x] Expected at least 1 space after "*"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceAfter)
 10 | ERROR | [x] Expected at least 1 space before "+"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceBefore)
 10 | ERROR | [x] Expected at least 1 space after "+"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceAfter)
 10 | ERROR | [x] Space found before comma in argument list (Generic.Functions.FunctionCallArgumentSpacing.SpaceBeforeComma)
 10 | ERROR | [x] No space found after comma in argument list (Generic.Functions.FunctionCallArgumentSpacing.NoSpaceAfterComma)
 10 | ERROR | [x] No space found after comma in argument list (Generic.Functions.FunctionCallArgumentSpacing.NoSpaceAfterComma)
 10 | ERROR | [x] Expected at least 1 space before "+"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceBefore)
 10 | ERROR | [x] Expected at least 1 space after "+"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceAfter)
 10 | ERROR | [x] Expected at least 1 space before "*"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceBefore)
 10 | ERROR | [x] Expected at least 1 space after "*"; 0 found (PSR12.Operators.OperatorSpacing.NoSpaceAfter)
 11 | ERROR | [x] Opening brace should be on a new line (Squiz.Functions.MultiLineFunctionDeclaration.BraceOnSameLine)
 11 | ERROR | [x] Closing brace must be on a line by itself (Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore)
```

And these for the third:
```
 15 | ERROR | [x] Opening brace should be on a new line (Squiz.Functions.MultiLineFunctionDeclaration.BraceOnSameLine)
 15 | ERROR | [x] Closing brace must be on a line by itself (Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore)
```

If I'd run the fixer, the code sample would be changed to read like this:
```php
<?php

class Foo
{
    << Attr1(2 * 3 + 3), Bar(4 + 5 * 2) >>
    << Attr2(2 * ( 3 + 3 ), Baz, ( 4 + 5 ) * 2) >>
    public function brackets()
    {
    }

    @@Attr1(2 * 3 + 3), Bar(4 + 5 * 2)
    @@Attr2(2 * ( 3 + 3 ), Baz, ( 4 + 5 ) * 2)
    public function atat()
    {
    }

    #[Attr1(2 * 3 + 3), Bar(4 + 5 * 2)]
    #[ Attr2 ( 2*( 3+3 ),Baz,( 4+5 )*2 ) ]
    public function hash()
    {
    }
}
```

### Conclusion

The take-away from this is that with both the first `<< >>` as well as with the second syntax `@@`, the attribute is treated like normal code _and fixed accordingly_. This shouldn't happen as PSR12 has no rules about attributes or attribute formatting and therefore the attribute code **_should be left alone_**.

With the third syntax `#[]`, the attribute _is_ left alone as it is regarded as a comment in PHP < 8.

Of course, PHPCS will (attempt to) backfill the syntax for PHP < 8 once things are stabilized / gone into feature freeze, but we all know that people don't always upgrade as quickly as we'd want them too, so with the first two syntaxes, both PHPCS as well as external standards can expect a barrage of support requests/complaints/bug reports/tirades about code being fixed incorrectly from people who haven't upgraded to the PHPCS version with full PHP 8 support (presuming that's been released yet).

While with the third syntax, most sniffs, save for some comment sniffs will ignore the attribute and things will be (relatively) calm.

#### Caveats

With multi-line attributes, we may still expect issues to be reported when the third syntax is used.

### Backfilling

As for the backfill, with the clear start `#[` and end `]` markers of the hash syntax, backfilling this will be relatively easy.

Same could be said for the original `<<...>>` syntax, though that would still take a lot more logic to make the distinction between when `<<` and `>>` are used as operators and when they are used as markers for attributes.

With the `@@` syntax, backfilling will be most difficult as there is no clear end to the attribute, so I expect any backfill for that syntax to be buggy for the next year or so, just like we're still getting occasional bug reports about the arrow function backfill, which in its own way suffered from the same problem (no clear scope opener/closer, which make backfilling especially difficult when nested or combined with ternaries and such).

**Comment by jrfnl** [comment]
Still forgot to mention something:

Regarding the BC break with `#` comments:
* First off, `#` comments are rare and the least used type of comment in PHP.
* Second, there are, and have been for years, sniffs which tell people not to use the `#` comment syntax.
* Third, if only `#[..]` will be seen as an attribute, i.e. with the brackets, I expect no problems at all as the chances of that character combination, without whitespace between the `#` and the `[`, occurring are infinitely small.

**Comment by jrfnl** [comment]
Oh and looking at some more examples, like the code @svpernova09 posted above, I do actually expect problems with the inline attributes when backfilling for the `#[]` syntax.

The problem in that case will be that the code after the attribute would be tokenized as a comment and would need to be "retokenized" as otherwise the PHPCS tokenizer won't be able to match up scope opener/scope closers and the likes, which would throw everything off.

I need to have a good think about how that is solvable (if at all).

Having said that, more than anything that would cause _underreporting_ by sniffs, which is still better than _overreach_ which is what I demonstrated above.

**Comment by jrfnl** [comment]
Pinging @gsherwood as he may have some thoughts about this as well.

**Comment by jrfnl** [comment]
@gsherwood For context, this is in response to the following Twitter conversations:
https://twitter.com/derickr/status/1285912223639130114
https://twitter.com/JoePFerguson/status/1286017011831771136

**Comment by gsherwood** [comment]
My strong preference is for the `#[]` syntax.

Square brackets are easy to match in pairs - you wont encounter a random square bracket closer without having seen it's opener yet, so easy to create a stack and match the attribute syntax for PHP < 8. The fact that it is regarded as a comment in older PHP versions is both good and bad, but I think this can be overcome by doing a second pass over the attribute content to get at the inner tokens. Needs some testing.

The current `@@` gives me nightmares just thinking about how to backfill that. I'm not entirely sure a backfill for it would ever be considered stable.

**Comment by svpernova09** [comment]
@jrfnl Thanks a ton! I'm planning on copy/pasting this into my RFC and linking to your comments as the source.

@gsherwood Thanks for reviewing!
